export const LOG_OUT = "LOG_OUT";
export const CLEAR_STORAGE = "CLEAR_STORAGE";
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const UPDATE_USER = "UPDATE_USER";

export const GET_PROFILE = "GET_PROFILE";
export const ADD_NEW_RECIPE = "ADD_NEW_RECIPE";
export const LOADING = "LOADING";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_IS_LOGIN = "SET_IS_LOGIN";

export const GET_ALL_RECIPES = "GET_ALL_RECIPES"
export const USER_RECIPES = "USER_RECIPES"
export const UPDATE_RECIPE = "UPDATE_RECIPE"
export const ADD_RECIPE = "ADD_RECIPE"
export const LOADING_RECIPE = "LOADING_RECIPE"
export const RECIPE_ERROR = "RECIPE_ERROR"
export const RESET_RECIPE_STATE = "RESET_RECIPE_STATE"

export const GET_ALL_BLOG = "GET_ALL_BLOG"
export const UPDATE_BLOG = "UPDATE_BLOG"
export const ADD_BLOG = "ADD_BLOG"
export const LOADING_BLOG = "LOADING_BLOG"
export const BLOG_ERROR = "BLOG_ERROR"
export const RESET_BLOG_STATE = "RESET_BLOG_STATE"

export const GET_ALL_SLIDER = "GET_ALL_SLIDER"
export const UPDATE_SLIDER = "UPDATE_SLIDER"
export const ADD_SLIDER = "ADD_SLIDER"
export const LOADING_SLIDER = "LOADING_SLIDER"
export const SLIDER_ERROR = "SLIDER_ERROR"
export const RESET_SLIDER_STATE = "RESET_SLIDER_STATE"

export const GET_ALL_PAGE = "GET_ALL_PAGE"
export const UPDATE_PAGE = "UPDATE_PAGE"
export const ADD_PAGE = "ADD_PAGE"
export const LOADING_PAGE = "LOADING_PAGE"
export const PAGE_ERROR = "PAGE_ERROR"
export const RESET_PAGE_STATE = "RESET_PAGE_STATE"

export const GET_ALL_ADVERT = "GET_ALL_ADVERT"
export const UPDATE_ADVERT = "UPDATE_ADVERT"
export const ADD_ADVERT = "ADD_ADVERT"
export const LOADING_ADVERT = "LOADING_ADVERT"
export const ADVERT_ERROR = "ADVERT_ERROR"
export const RESET_ADVERT_STATE = "RESET_ADVERT_STATE"

export const GET_ALL_NEWSLETTER = "GET_ALL_NEWSLETTER"
export const LOADING_NEWSLETTER = "LOADING_NEWSLETTER"
export const NEWSLETTER_ERROR = "NEWSLETTER_ERROR"

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const LOADING_CATEGORY = "LOADING_CATEGORY"
export const CATEGORY_ERROR = "CATEGORY_ERROR"
export const RESET_CATEGORY_STATE = "RESET_CATEGORY_STATE"

export const ADMIN_LOGIN = "ADMIN_LOGIN"
export const ADMIN_LOGOUT = "ADMIN_LOGOUT"
export const ADMIN_ADD_USER = "ADMIN_ADD_USER"
export const ADMIN_ADD_ADMIN = "ADMIN_ADD_ADMIN"
export const ADMIN_UPDATE_USERS = "ADMIN_UPDATE_USERS"
export const GET_ALL_ADMIN = "GET_ALL_ADMIN"
export const GET_ALL_USER = "GET_ALL_USER"
export const GET_CURRENT_ADMIN = "GET_CURRENT_ADMIN"
export const GET_SELECTED_USER = "GET_SELECTED_USER"
export const LOADING_USER = "LOADING_USER"
export const USER_ERROR = "USER_ERROR"
export const RESET_USER_STATE = "RESET_USER_STATE"
export const ADD_INPUT = "ADD_INPUT"

export const ANIN_LOGIN = "ANIN_LOGIN"
