import moment from "moment";
import * as GiIcons from "react-icons/gi";
import * as BiIcons from "react-icons/bi";
import * as FaIcons from "react-icons/fa";
import * as SiIcons from "react-icons/si";

export const record = [
   { id: Math.floor(Math.random() * 10000),  title: "Choclate Cake Cream", image: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80" },,
   { id: Math.floor(Math.random() * 10000),  title: "Shrimp Scampi Bake", image: "https://media.istockphoto.com/photos/preparing-frittata-with-paprika-spring-onions-peas-spinach-and-picture-id965002050?k=20&m=965002050&s=170667a&w=0&h=0w-_s4h_WruKNit9LYY5P0v-whLw_Sr3JcrrV2Um0nw=" },,
   { id: Math.floor(Math.random() * 10000),  title: "Choclate Cake Cream", image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=400&q=60" },
   { id: Math.floor(Math.random() * 10000),  title: "Garlic Shrimp Linguine ", image: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDV8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=400&q=60" },
   { id: Math.floor(Math.random() * 10000),  title: "Garlic Shrimp Linguine ", image: "https://images.unsplash.com/photo-1455099229380-7b52707e356a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDh8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=400&q=60" },
   { id: Math.floor(Math.random() * 10000),  title: "Shrip Scampi with Pasta ", image: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEyfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=400&q=60" },
   { id: Math.floor(Math.random() * 10000),  title: "Choclate Cake Cream", image: "https://images.unsplash.com/photo-1556911073-52527ac43761?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=400&q=60" },
];
export const adminUser = [
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2021/05/23/00/21/woman-6274879__340.png",
    username: "Elisa Iken",
    usergroup: "Admin",
    status: "Active",
    view: "134",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2020/06/10/02/22/caricature-5280770__340.jpg",
    username: "Maroo Keb",
    usergroup: "Admin",
    status: "Active",
    view: "54",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2016/04/26/12/25/male-1354358__340.png",
    username: "Kabir Moon",
    usergroup: "Admin",
    status: "Active",
    view: "93",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2014/04/03/10/32/user-310807__340.png",
    username: "Raers Tiy",
    usergroup: "Admin",
    status: "Active",
    view: "23",
    date: moment().format("l"),
  },
];
export const user = [
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2021/05/23/00/21/woman-6274879__340.png",
    username: "Elisa Iken",
    usergroup: "User",
    status: "Active",
    view: "134",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2020/06/10/02/22/caricature-5280770__340.jpg",
    username: "Maroo Keb",
    usergroup: "User",
    status: "Inactive",
    view: "54",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2016/04/26/12/25/male-1354358__340.png",
    username: "Kabir Moon",
    usergroup: "User",
    status: "Active",
    view: "93",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2014/04/03/10/32/user-310807__340.png",
    username: "Raers Tiy",
    usergroup: "User",
    status: "Active",
    view: "23",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2021/05/23/00/21/woman-6274879__340.png",
    username: "Elisa Iken",
    usergroup: "User",
    status: "Active",
    view: "134",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2021/05/23/00/21/woman-6274879__340.png",
    username: "Elisa Iken",
    usergroup: "User",
    status: "Active",
    view: "134",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2020/06/10/02/22/caricature-5280770__340.jpg",
    username: "Maroo Keb",
    usergroup: "User",
    status: "Inactive",
    view: "54",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2016/04/26/12/25/male-1354358__340.png",
    username: "Kabir Moon",
    usergroup: "User",
    status: "Active",
    view: "93",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2014/04/03/10/32/user-310807__340.png",
    username: "Raers Tiy",
    usergroup: "User",
    status: "Active",
    view: "23",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2021/05/23/00/21/woman-6274879__340.png",
    username: "Elisa Iken",
    usergroup: "User",
    status: "Active",
    view: "134",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2020/06/10/02/22/caricature-5280770__340.jpg",
    username: "Maroo Keb",
    usergroup: "User",
    status: "Active",
    view: "54",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2016/04/26/12/25/male-1354358__340.png",
    username: "Kabir Moon",
    usergroup: "User",
    status: "Inactive",
    view: "93",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2014/04/03/10/32/user-310807__340.png",
    username: "Raers Tiy",
    usergroup: "User",
    status: "Active",
    view: "23",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2021/05/23/00/21/woman-6274879__340.png",
    username: "Elisa Iken",
    usergroup: "User",
    status: "Inactive",
    view: "134",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2020/06/10/02/22/caricature-5280770__340.jpg",
    username: "Maroo Keb",
    usergroup: "User",
    status: "Active",
    view: "54",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2016/04/26/12/25/male-1354358__340.png",
    username: "Kabir Moon",
    usergroup: "User",
    status: "Active",
    view: "93",
    date: moment().format("l"),
  },
   { id: Math.floor(Math.random() * 10000), 
    image:
      "https://cdn.pixabay.com/photo/2014/04/03/10/32/user-310807__340.png",
    username: "Raers Tiy",
    usergroup: "User",
    status: "Inactive",
    view: "23",
    date: moment().format("l"),
  },
];
export const recipes = [
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "cake",
    title: "Tortellini with  and Pancetta",
    published: "maroo",
    status: "Inactive",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "kid",
    title: "Tortellini with Peas and Pancetta",
    published: "sstt",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Inactive",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Inactive",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Inactive",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
   { id: Math.floor(Math.random() * 10000), 
    category: "Healthy",
    title: "Tortellini with Peas and Pancetta",
    published: "maroo",
    status: "Active",
  },
];
export const iconData = [
   {name: "Beef", icon: <GiIcons.GiMeat /> },
   {name: "Bread", icon: <GiIcons.GiSlicedBread /> },
   {name: "Cake", icon: <GiIcons.GiCakeSlice /> },
   {name: "Healthy", icon: <GiIcons.GiStrong /> },
   {name: "Category", icon: <BiIcons.BiCategory /> },
   {name: "Coffee", icon: <BiIcons.BiCoffeeTogo /> },
   {name: "Cookie", icon: <BiIcons.BiCookie /> },
   {name: "Cupcake", icon: <GiIcons.GiCupcake /> },
   {name: "Drinks", icon: <BiIcons.BiDrink /> },
   {name: "Equipment", icon: <SiIcons.SiJusteat /> },
   {name: "Fish", icon: <GiIcons.GiFriedFish /> },
   {name: "Ice Cream", icon: <FaIcons.FaIceCream /> },
   {name: "Kids", icon: <BiIcons.BiSmile /> },
   {name: "Pasta", icon: <FaIcons.FaPastafarianism /> },
   {name: "Pizza", icon: <FaIcons.FaPizzaSlice /> },
   {name: "Pork", icon: <GiIcons.GiPig /> },
   {name: "Salad", icon: <SiIcons.SiFoodpanda /> },
   {name: "Sea Food", icon: <GiIcons.GiSeaTurtle /> },
   {name: "Equipment", icon: <SiIcons.SiJusteat /> },
   {name: "Shrimps", icon: <GiIcons.GiShrimp /> },
   {name: "Heathy", icon: <GiIcons.GiStrong /> },
   {name: "Snacks", icon: <FaIcons.FaCookie /> },
   {name: "Soup", icon: <GiIcons.GiBlender /> },
   {name: "Tea", icon: <SiIcons.SiGitea /> },
];
export const categories = [
   { id: Math.floor(Math.random() * 10000),  name: "Beef", icon: <GiIcons.GiMeat /> },
   { id: Math.floor(Math.random() * 10000),  name: "Bread", icon: <GiIcons.GiSlicedBread /> },
   { id: Math.floor(Math.random() * 10000),  name: "Cake", icon: <GiIcons.GiCakeSlice /> },
   { id: Math.floor(Math.random() * 10000),  name: "Healthy", icon: <GiIcons.GiStrong /> },
   { id: Math.floor(Math.random() * 10000),  name: "Category 1", icon: <BiIcons.BiCategory /> },
   { id: Math.floor(Math.random() * 10000),  name: "Category 2", icon: <BiIcons.BiCategory /> },
   { id: Math.floor(Math.random() * 10000),  name: "Category 3", icon: <BiIcons.BiCategory /> },
   { id: Math.floor(Math.random() * 10000),  name: "Category 4", icon: <BiIcons.BiCategory /> },
   { id: Math.floor(Math.random() * 10000),  name: "Category 5", icon: <BiIcons.BiCategory /> },
   { id: Math.floor(Math.random() * 10000),  name: "Category 6", icon: <BiIcons.BiCategory /> },
   { id: Math.floor(Math.random() * 10000),  name: "Chicken", icon: <GiIcons.GiRoastChicken /> },
   { id: Math.floor(Math.random() * 10000),  name: "Coffee", icon: <BiIcons.BiCoffeeTogo /> },
   { id: Math.floor(Math.random() * 10000),  name: "Cookie", icon: <BiIcons.BiCookie /> },
   { id: Math.floor(Math.random() * 10000),  name: "Cupcake", icon: <GiIcons.GiCupcake /> },
   { id: Math.floor(Math.random() * 10000),  name: "Drinks", icon: <BiIcons.BiDrink /> },
   { id: Math.floor(Math.random() * 10000),  name: "Equipment", icon: <SiIcons.SiJusteat /> },
   { id: Math.floor(Math.random() * 10000),  name: "Fish", icon: <GiIcons.GiFriedFish /> },
   { id: Math.floor(Math.random() * 10000),  name: "Ice Cream", icon: <FaIcons.FaIceCream /> },
   { id: Math.floor(Math.random() * 10000),  name: "Kids", icon: <BiIcons.BiSmile /> },
   { id: Math.floor(Math.random() * 10000),  name: "Pasta", icon: <FaIcons.FaPastafarianism /> },
   { id: Math.floor(Math.random() * 10000),  name: "Pizza", icon: <FaIcons.FaPizzaSlice /> },
   { id: Math.floor(Math.random() * 10000),  name: "Pork", icon: <GiIcons.GiPig /> },
   { id: Math.floor(Math.random() * 10000),  name: "Salad", icon: <SiIcons.SiFoodpanda /> },
   { id: Math.floor(Math.random() * 10000),  name: "Sea Food", icon: <GiIcons.GiSeaTurtle /> },
   { id: Math.floor(Math.random() * 10000),  name: "Equipment", icon: <SiIcons.SiJusteat /> },
   { id: Math.floor(Math.random() * 10000),  name: "Shrimps", icon: <GiIcons.GiShrimp /> },
   { id: Math.floor(Math.random() * 10000),  name: "Heathy", icon: <GiIcons.GiStrong /> },
   { id: Math.floor(Math.random() * 10000),  name: "Snacks", icon: <FaIcons.FaCookie /> },
   { id: Math.floor(Math.random() * 10000),  name: "Soup", icon: <GiIcons.GiBlender /> },
   { id: Math.floor(Math.random() * 10000),  name: "Tea", icon: <SiIcons.SiGitea /> },
];
export const newsletter = [
   { id: Math.floor(Math.random() * 10000),  email: "marwa.elmanxxxawy91@gmail.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "marwa.elmanawy91@gmail.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "marwa.elmenawy91rrrtr@gmail.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "a.khalid@tocaan.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "marwa@elmanawy.info", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "maroo@n.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@adffmin.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@rrrrrrrrrrardmin.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admin.comttttttttttttttt", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admin.rrrr", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admin.com4444444444", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admsdsdin.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "vdfvfd@dkv.vcvff", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admifffn@admin.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "meme@gmail.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "marwa.elmanawy91@gmail.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "marwa.elmenawy91rrrtr@gmail.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "a.khalid@tocaan.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "marwa@elmanawy.info", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "maroo@n.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@adffmin.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@rrrrrrrrrrardmin.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admin.comttttttttttttttt", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admin.rrrr", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admin.com4444444444", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admin@admsdsdin.com", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "vdfvfd@dkv.vcvff", created: "2019-05-18 02:18:21" },
   { id: Math.floor(Math.random() * 10000),  email: "admifffn@admin.com", created: "2019-05-18 02:18:21" },
];
export const advertisement = [
   { id: Math.floor(Math.random() * 10000), 
    title: "Tricks side 2",
    type: "image",
    location: "Tricks Side 2",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Tricks side 1",
    type: "code",
    location: "Tricks Side 1",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Trick side 2",
    type: "code",
    location: "Trick Side 2",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Trick side 1",
    type: "code",
    location: "Trick Side 1",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Recipe side 2",
    type: "code",
    location: "Recipe Side 2",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Recipe side 1",
    type: "code",
    location: "Recipe Side 1",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Home side 2",
    type: "code",
    location: "Home Side 2",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Trick footer",
    type: "code",
    location: "Trick Footer",
    created: "May 22, 2016 09:51:13 AM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Recipe footer",
    type: "code",
    location: "Recipe Footer",
    created: "May 22, 2016 09:51:13 AM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Recipes footer",
    type: "code",
    location: "Recipes Footer",
    created: "May 22, 2016 09:51:13 AM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Tricks Footer",
    type: "code",
    location: "Tricks Footer",
    created: "May 22, 2016 09:51:13 AM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "category footer",
    type: "code",
    location: "Category Footer",
    created: "Apr 26, 2018 01:45:38 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Home side 1",
    type: "code",
    location: "Home Side 1",
    created: "Apr 26, 2018 01:32:21 PM",
  },
   { id: Math.floor(Math.random() * 10000), 
    title: "Home footer",
    type: "code",
    location: "Home Footer",
    created: "May 22, 2016 09:51:13 AM",
  },
];
export const page = [
     { id: Math.floor(Math.random() * 10000), title:'About Us', permlink: 'about-us' , content: 'How browsing and membership works Browsing: You need to be 13 years or over to browse the Envato Market sites. We don’t knowingly collect any information from anyone aged 13 or under. When browsing the sites you agree to follow our guidelines or instructions and keep in mind that these terms apply to any use of our Envato Market sites whether or not you’re a member. Membership    7. Age: You need to be 18 years or over to become a member or to buy items as a Guest. If you’re under 18 you will need to get a parent or guardian to buy items as a Guest or use the account of a parent or legal guardian who is at least 18 years of age, with their permission, and this adult will be responsible for all your activities. 8. Envato Account: Membership is free. When you become a member you get an Envato Market account that is accessible from any of our Envato Market sites (and is also your Envato account for other Envato services). Your membership will allow you to ‘buy’ (license) items from authors, participate in our online forums, and generally contribute to our ecosystem of Envato Market sites that help people get creative. Membership also gives you the opportunity to become an author (see section 30 – Becoming an Author) or earn referral income (see section 10 – Referrals). 9. Guest Checkout: You may purchase an item from any of our Envato Market sites as a Guest. Unless otherwise stated, these terms and conditions apply to Guests in the same way they apply to buyers who have an Envato Market account. Guests don’t receive an Envato Market account, but can of course register for one at any time. If you buy items as a Guest, your access to our ecosystem will be limited.',},	 
     { id: Math.floor(Math.random() * 10000), title:'Licenses',	 permlink: 'Licenses' , content: 'Your responsibility: You promise that information you give us is true, accurate and complete and, if you sign up for an Envato Market account, that you will keep your account information up-to-date (including a current email address). Your membership is not transferrable. You are responsible for any use of the Envato Market sites including any activity that occurs in conjunction with your username and password, if you have an Envato Market account, so keep your password secure and don’t let any other person use your username or password. If you realise there’s any unauthorized use of your password or any breach of security you need to let us know immediately. ',},
     { id: Math.floor(Math.random() * 10000), title:'Privacy Policy',	 permlink: 'privacy-policy' , content: 'Envato’s ecosystem of digital marketplaces helps millions of people around the world get creative and earn online. When you create an account and accept these terms you become a member of our community. You will have that will allow you to buy and sell items like the ones found on the Envato Market sites and make other related transactions. You can also buy items on Envato Market as a Guest.',},
     { id: Math.floor(Math.random() * 10000), title:'Terms & Condition',permlink: 'terms-&-ondition' , content: 'me a member or to buy items as a Guest. If you’re under 18 you will need to get a parent or guardian to buy items as a Guest or use the account of a parent or legal guardian who is at least 18 years of age, with their permission, and this adult will be responsible for all your activities. 8. Envato Account: Membership is free. When you become a member you get an Envato Market account that is accessible from any of our Envato Market sites (and is also your Envato account for other Envato services). Your membership will allow you to ‘buy’ (license) items from authors, participate in our online forums, and generally contribute to our ecosystem of Envato Market sites that help people get creative. Membership also gives you the opportunity to become an author (see section 30 – Becoming an ',},
];
export const blog = [
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '97'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '72'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '56'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '25'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '78'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '20'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '2'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '22'},
 { id: Math.floor(Math.random() * 10000), topic: 'how to create cake', visit: '12'},
];